---
  - name: "Remove user {{ item.name }}"
    user:
      name: "{{ item.name }}"
      uid: "{{ item.uid }}"
      state: absent
      remove: "{{ item.remove | default('False') }}"

  - name: "Remove group {{ item.name }}"
    group:
      name: "{{ item.name }}"
      gid: "{{ item.uid }}"
      state: absent
