---
- name: "Remove user {{ item.name }}"
  become: true
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    state: absent
    remove: "{{ item.remove | default('False') }}"

- name: "Remove group {{ item.name }}"
  become: true
  group:
    name: "{{ item.name }}"
    gid: "{{ item.uid }}"
    state: absent
