sudo: required
language: python
python:
- '2.7'
env:
  global:
  - MOLECULE_VERSION='1.25.0'
  - DOCKER_VERSION='2.2.1'
  - TESTINFRA_VERSION='1.6.4'
  matrix:
  - ANSIBLE_VERSION='latest'
  - ANSIBLE_VERSION='2.3.0'
  - ANSIBLE_VERSION='2.2.0'
  - ANSIBLE_VERSION='2.1.0'
services:
- docker
install:
- pip install --upgrade pip
- if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install
  ansible==$ANSIBLE_VERSION; fi
- ansible --version
- pip install molecule==$MOLECULE_VERSION
- pip install docker==$DOCKER_VERSION
- pip install testinfra==$TESTINFRA_VERSION
script:
- molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: IlgH8PlCQSdEwqDQwbtVE++DEbL9cYJI64gp2i92lYv5clG70DMp0jnC1V1i8VzPCQb0da2ZQMi3ZyTAPtDFcJMkEPLQUU40AhT+1yL9Pxu6V8XGlCSsV4fdcSzxyUcwn0HDxrcnlinNxluEuunTLRvqdrYFVdSRNQCyxa3X6QBbjrttbhwE0jxqev2IoxzadpJPDLwJWxFm5wHj5tInK6HiEsiyqX0AL+pRfBDtL65J2UYFa4oUZD1jVlhgFcNUF43uRqNgr/AugFB4RngUT9JMaNGwPYeCZ+hz2gk+fEKOvTpeOKftBh9JzK1MBHzwyTnoBusspK2prsS0YosseHO3Y0I9Gi5cj0tGS0zhcwxkP1ZHMLCcrRzTPjySPH3s5lOovpMZ7MYBXtQTgYG/vCSLgLj3jMQzwCCOT2Kn//9Ls8Z+0aqProF3BqoEEn4zrXD3tGNjMHhGXkf8VXgBO7d8ArJjeE/3PXZCWBMzmn50bpIaYWbSDo0O/U1mMuNs8UoSLfdjkh/bh6WwvXMQakPDqiawQPXZTHjSpkMPgVmmZYovwIwQGGPRrhGsWFv9ycF1/YMv7b1O5fGj9/fp7nEjy1SqLIFVXA5rtn0UtG/63GLH+Igs5ef8iNmTSldzhLTqpiJ7ZJiyQ9dmxby0c8IAf+/dXqxS85zr7gYrvho=
