---
  - name: "Create group {{ item.name }}"
    group:
      name: "{{ item.name }}"
      gid: "{{ item.gid | default(omit) }}"
      state: present
      system: "{{ item.is_system | default('False') }}"
