---
- name: Install Prerequisites
  hosts: all
  gather_facts: False
  become: True

  tasks:
    - name: FreeBSD | Is pkgng bootstrapped?
      raw: /usr/sbin/pkg -N
      register: pkg
      ignore_errors: True
      changed_when: False

    - name: FreeBSD | Bootstrap pkgng
      raw: /usr/bin/env ASSUME_ALWAYS_YES=1 /usr/sbin/pkg bootstrap -f
      when: pkg|failed

    - name: FreeBSD | Is python27 installed?
      raw: /bin/test -f /usr/local/bin/python2.7
      register: python27
      ignore_errors: True
      changed_when: False

- name: Accounts Testing Playbook
  hosts: all

  vars:
    ansible_python_interpreter: /usr/local/bin/python2.7
    accounts_groups:
      - name: monkeys
        gid: 2000
    accounts_users:
      - name: tmonkey1
        comment: 'Test Monkey 1'
        uid: 1006
        password:
          OpenBSD: "$2b$08$3eBhGgrLIXZP8Ewh8tqXtuh38M463K2rKYJSyUgATRKQNX70b2jyG"
          FreeBSD: "$1$N0JqVxf/$iSmuQ6lyKB/GJUe52DqFw/"
          RedHat: "$1$N0JqVxf/$iSmuQ6lyKB/GJUe52DqFw/"
        groups:
          - wheel
        authorized_keys:
          - key: 'ssh-dss FAKEKEYSUTFF== tmonkey1'
            state: present
      - name: tmonkey2
        comment: 'Test Monkey 2'
        uid: 1007
        password:
          OpenBSD: "$2b$08$3eBhGgrLIXZP8Ewh8tqXtuh38M463K2rKYJSyUgATRKQNX70b2jyG"
          FreeBSD: "$1$N0JqVxf/$iSmuQ6lyKB/GJUe52DqFw/"
          RedHat: "$1$N0JqVxf/$iSmuQ6lyKB/GJUe52DqFw/"
        groups:
          - wheel
        authorized_keys:
          - key: 'ssh-dss FAKEKEYSUTFF== tmonkey2'
            state: present
      - name: tmonkey3
        comment: 'Test Monkey 3'
        uid: 1008
        password: "$1$N0JqVxf/$iSmuQ6lyKB/GJUe52DqFw/"
        group: monkeys
        groups:
          - wheel
        authorized_keys:
          - key: 'ssh-dss FAKEKEYSUTFF== tmonkey3'
            state: present

  roles:
    - {role: ansible-role-accounts}

